/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.util.serie.seriemaven.gui;

import at.util.serie.seriemaven.IMDB;
import at.util.serie.seriemaven.Serie;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.swing.JOptionPane;
import org.springframework.stereotype.Component;

/**
 *
 * @author RUDI
 */
@Component
public class AddSeriesPanel extends javax.swing.JPanel {

    @Resource
    IMDB imdb;
    @Resource
    MainFrame mainFrame;
    List<Serie> series;

    /**
     * Creates new form AddSeriesToConfig
     */
    public AddSeriesPanel() {
    }

    @PostConstruct
    public void init() {
        initComponents();

        series = imdb.readSeriesFromConfig();
        showSeriesInTxtArea();
    }

    private void showSeriesInTxtArea() {
        txtSeries.setText("");
        for (Serie serie : series) {
            txtSeries.append(serie.getTitle() + "\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        txtSeries = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Vorhandene Serien"));
        setLayout(new java.awt.GridBagLayout());

        txtSeries.setColumns(20);
        txtSeries.setRows(5);
        jScrollPane1.setViewportView(txtSeries);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/onebit_11.png"))); // NOI18N
        btnSave.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(btnSave, gridBagConstraints);

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/onebit_33.png"))); // NOI18N
        btnUndo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(btnUndo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        List<Serie> series = new ArrayList<Serie>();
        String[] text = txtSeries.getText().split("\\n");
        Serie serie = null;
        for (int i = 0; i < text.length; i++) {
            serie = new Serie();
            serie.setTitle(text[i]);
            series.add(serie);
        }
        if (imdb.writeSeriesInConfig(series)) {
            JOptionPane.showMessageDialog(mainFrame, "Es wurden " + series.size() + " Serien gespeichert");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        showSeriesInTxtArea();
    }//GEN-LAST:event_btnUndoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtSeries;
    // End of variables declaration//GEN-END:variables
}
