/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.util.serie.seriemaven.gui;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.swing.JPanel;
import org.springframework.stereotype.Component;

/**
 *
 * @author RUDI
 */
@Component
public class MainPanel extends javax.swing.JPanel {

    @Resource
    AddSeriesPanel addSeriesPanel;
    
    @Resource
    OverviewPanel overviewPanel;

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
    }

    @PostConstruct
    public void init() {
        initComponents();
        add(overviewPanel, "Overview");
        add(addSeriesPanel, "Config");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
