/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package at.util.serie.seriemaven.gui;

import java.awt.CardLayout;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import org.springframework.stereotype.Component;

/**
 *
 * @author RUDI
 */
@Component
public class MenuPanel extends javax.swing.JPanel {
    
    @Resource
    MainPanel mainPanel;
    
    /**
     * Creates new form MenuPanel
     */
    public MenuPanel() {
        
    }
    
    @PostConstruct
    public void init() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSerieConfig = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout());

        jButton1.setText("jButton1");
        add(jButton1);

        jButton2.setText("jButton2");
        add(jButton2);

        btnSerieConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/onebit_39.png"))); // NOI18N
        btnSerieConfig.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSerieConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerieConfigActionPerformed(evt);
            }
        });
        add(btnSerieConfig);

        jButton4.setText("jButton4");
        add(jButton4);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSerieConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerieConfigActionPerformed
       CardLayout layout =  (CardLayout) mainPanel.getLayout();
       layout.show(mainPanel, "Config");
    }//GEN-LAST:event_btnSerieConfigActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSerieConfig;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
